<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LP-5CD212M0Y5" failures="1" tests="3" name="ScrapperTests2" time="18.627" errors="0" timestamp="2025-08-08T13:55:51 IST">
  <testcase classname="OG_image.ScrappersLinkedIn" name="LikedInLanding" time="15.121"/>
  <testcase classname="OG_image.ScrappersLinkedIn" name="LinkedInPostInception" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.io.FileNotFoundException: .\azure-deploy\wwwroot\uploads\Phase2URLs.xlsx (The process cannot access the file because it is being used by another process)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: .\azure-deploy\wwwroot\uploads\Phase2URLs.xlsx (The process cannot access the file because it is being used by another process)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.FileNotFoundException: .\azure-deploy\wwwroot\uploads\Phase2URLs.xlsx (The process cannot access the file because it is being used by another process)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
at OG_image.DBScrappers.needTotestUrls(DBScrappers.java:19)
... 19 more
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- LinkedInPostInception -->
  <testcase classname="OG_image.ScrappersLinkedIn" name="logLastLine" time="0.0">
    <skipped/>
  </testcase> <!-- logLastLine -->
</testsuite> <!-- ScrapperTests2 -->
